# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{script_finder}
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tobias Crawley"]
  s.date = %q{2010-12-26}
  s.email = %q{tcrawley@gmail.com}
  s.executables = ["r", "s"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    "README.textile",
    "VERSION.yml",
    "bin/r",
    "bin/s",
    "lib/#script_finder.rb#",
    "lib/script_finder.rb",
    "lib/script_finder/base_finder.rb",
    "lib/script_finder/rails_finder.rb",
    "lib/script_finder/script_finder.rb",
    "lib/utilities/script_utilities.rb",
    "test/finder_base_test.rb",
    "test/test_helper.rb",
    "test/utilities_test.rb"
  ]
  s.homepage = %q{http://github.com/tobias/script_finder}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A gem that provides tools to find and execute scripts in a project.}
  s.test_files = [
    "test/finder_base_test.rb",
    "test/test_helper.rb",
    "test/utilities_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

