# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{script_finder}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tobias Crawley"]
  s.date = %q{2010-08-03}
  s.default_executable = %q{s}
  s.email = %q{tcrawley@gmail.com}
  s.executables = ["s"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    "README.textile",
     "VERSION.yml",
     "bin/s",
     "lib/script_finder.rb",
     "lib/script_finder/script_finder.rb",
     "test/script_finder_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/tobias/script_finder}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A gem that provides tools to find and execute scripts in a project.}
  s.test_files = [
    "test/script_finder_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

